blueprint:
  name: 键盘遥控器
  description: '键盘遥控器'
  domain: automation
  source_url: https://github.com/shaonianzhentan/ha-docs/blob/master/blueprint/keyboard_remote.yaml
  input:
    key_1:
      name: Key 1
      description: 按键1
      default: []
      selector:
        action: {}
mode: restart
max_exceeded: silent
trigger:
- platform: event
  event_type: keyboard_remote_command_received
  event_data:
    device_descriptor: "/dev/input/event3"
action:
- variables:
    command: '{{ trigger.event.data.key_code }}'
- choose:
  - conditions:
    - '{{ command == ''65'' }}'
    sequence: !input 'key_1'