blueprint:
  name: Aqara Opple 无线开关
  description: 'ZHA里的Aqara Opple 6键开关的操作'
  domain: automation
  source_url: https://github.com/shaonianzhentan/ha-docs
  input:
    switch:
      name: Aqara switch
      description: Aqara switch to use
    button_1_remote_button_alt_short_press:
      name: Button 1 - single click
      description: 键1单击
      default: []
      selector:
        action: {}
    button_1_remote_button_alt_double_press:
      name: Button 1 - double click
      description: 键1双击
      default: []
      selector:
        action: {}
    button_1_remote_button_triple_press:
      name: Button 1 - triple click
      description: 键1三连击
      default: []
      selector:
        action: {}
    button_1_remote_button_alt_long_press:
      name: Button 1 - hold click
      description: 键1长按
      default: []
      selector:
        action: {}
    button_1_remote_button_long_release:
      name: Button 1 - release click
      description: 键1放开
      default: []
      selector:
        action: {}
    button_2_remote_button_alt_short_press:
      name: Button 2 - single click
      description: 键2单击
      default: []
      selector:
        action: {}
    button_2_remote_button_alt_double_press:
      name: Button 2 - double click
      description: 键2双击
      default: []
      selector:
        action: {}
    button_2_remote_button_triple_press:
      name: Button 2 - triple click
      description: 键2三连击
      default: []
      selector:
        action: {}
    button_2_remote_button_alt_long_press:
      name: Button 2 - hold click
      description: 键2长按
      default: []
      selector:
        action: {}
    button_2_remote_button_long_release:
      name: Button 2 - release click
      description: 键2放开
      default: []
      selector:
        action: {}
    button_3_remote_button_alt_short_press:
      name: Button 3 - single click
      description: 键3单击
      default: []
      selector:
        action: {}
    button_3_remote_button_alt_double_press:
      name: Button 3 - double click
      description: 键3双击
      default: []
      selector:
        action: {}
    button_3_remote_button_triple_press:
      name: Button 3 - triple click
      description: 键3三连击
      default: []
      selector:
        action: {}
    button_3_remote_button_alt_long_press:
      name: Button 3 - hold click
      description: 键3长按
      default: []
      selector:
        action: {}
    button_3_remote_button_long_release:
      name: Button 3 - release click
      description: 键3放开
      default: []
      selector:
        action: {}
    button_4_remote_button_alt_short_press:
      name: Button 4 - single click
      description: 键4单击
      default: []
      selector:
        action: {}
    button_4_remote_button_alt_double_press:
      name: Button 4 - double click
      description: 键4双击
      default: []
      selector:
        action: {}
    button_4_remote_button_triple_press:
      name: Button 4 - triple click
      description: 键4三连击
      default: []
      selector:
        action: {}
    button_4_remote_button_alt_long_press:
      name: Button 4 - hold click
      description: 键4长按
      default: []
      selector:
        action: {}
    button_4_remote_button_long_release:
      name: Button 4 - release click
      description: 键4放开
      default: []
      selector:
        action: {}
    button_5_remote_button_alt_short_press:
      name: Button 5 - single click
      description: 键5单击
      default: []
      selector:
        action: {}
    button_5_remote_button_alt_double_press:
      name: Button 5 - double click
      description: 键5双击
      default: []
      selector:
        action: {}
    button_5_remote_button_triple_press:
      name: Button 5 - triple click
      description: 键5三连击
      default: []
      selector:
        action: {}
    button_5_remote_button_alt_long_press:
      name: Button 5 - hold click
      description: 键5长按
      default: []
      selector:
        action: {}
    button_5_remote_button_long_release:
      name: Button 5 - release click
      description: 键5放开
      default: []
      selector:
        action: {}
    button_6_remote_button_alt_short_press:
      name: Button 6 - single click
      description: 键6单击
      default: []
      selector:
        action: {}
    button_6_remote_button_alt_double_press:
      name: Button 6 - double click
      description: 键6双击
      default: []
      selector:
        action: {}
    button_6_remote_button_triple_press:
      name: Button 6 - triple click
      description: 键6三连击
      default: []
      selector:
        action: {}
    button_6_remote_button_alt_long_press:
      name: Button 6 - hold click
      description: 键6长按
      default: []
      selector:
        action: {}
    button_6_remote_button_long_release:
      name: Button 6 - release click
      description: 键6放开
      default: []
      selector:
        action: {}
mode: restart
max_exceeded: silent
trigger:
- platform: device
  domain: zha
  device_id: !input 'switch'
action:
- variables:
    command: '{{ trigger.subtype }}_{{ trigger.type }}'
- choose:
  - conditions:
    - '{{ command == ''button_1_remote_button_alt_short_press'' }}'
    sequence: !input 'button_1_remote_button_alt_short_press'
  - conditions:
    - '{{ command == ''button_1_remote_button_alt_double_press'' }}'
    sequence: !input 'button_1_remote_button_alt_double_press'
  - conditions:
    - '{{ command == ''button_2_remote_button_alt_short_press'' }}'
    sequence: !input 'button_2_remote_button_alt_short_press'
  - conditions:
    - '{{ command == ''button_3_remote_button_alt_short_press'' }}'
    sequence: !input 'button_3_remote_button_alt_short_press'
  - conditions:
    - '{{ command == ''button_4_remote_button_alt_short_press'' }}'
    sequence: !input 'button_4_remote_button_alt_short_press'
  - conditions:
    - '{{ command == ''button_5_remote_button_alt_short_press'' }}'
    sequence: !input 'button_5_remote_button_alt_short_press'
  - conditions:
    - '{{ command == ''button_6_remote_button_alt_short_press'' }}'
    sequence: !input 'button_6_remote_button_alt_short_press'
  - conditions:
    - '{{ command == ''button_2_remote_button_alt_double_press'' }}'
    sequence: !input 'button_2_remote_button_alt_double_press'
  - conditions:
    - '{{ command == ''button_3_remote_button_alt_double_press'' }}'
    sequence: !input 'button_3_remote_button_alt_double_press'
  - conditions:
    - '{{ command == ''button_4_remote_button_alt_double_press'' }}'
    sequence: !input 'button_4_remote_button_alt_double_press'
  - conditions:
    - '{{ command == ''button_5_remote_button_alt_double_press'' }}'
    sequence: !input 'button_5_remote_button_alt_double_press'
  - conditions:
    - '{{ command == ''button_6_remote_button_alt_double_press'' }}'
    sequence: !input 'button_6_remote_button_alt_double_press'
  - conditions:
    - '{{ command == ''button_1_remote_button_triple_press'' }}'
    sequence: !input 'button_1_remote_button_triple_press'
  - conditions:
    - '{{ command == ''button_2_remote_button_triple_press'' }}'
    sequence: !input 'button_2_remote_button_triple_press'
  - conditions:
    - '{{ command == ''button_3_remote_button_triple_press'' }}'
    sequence: !input 'button_3_remote_button_triple_press'
  - conditions:
    - '{{ command == ''button_4_remote_button_triple_press'' }}'
    sequence: !input 'button_4_remote_button_triple_press'
  - conditions:
    - '{{ command == ''button_5_remote_button_triple_press'' }}'
    sequence: !input 'button_5_remote_button_triple_press'
  - conditions:
    - '{{ command == ''button_6_remote_button_triple_press'' }}'
    sequence: !input 'button_6_remote_button_triple_press'
  - conditions:
    - '{{ command == ''button_1_remote_button_alt_long_press'' }}'
    sequence: !input 'button_1_remote_button_alt_long_press'
  - conditions:
    - '{{ command == ''button_2_remote_button_alt_long_press'' }}'
    sequence: !input 'button_2_remote_button_alt_long_press'
  - conditions:
    - '{{ command == ''button_3_remote_button_alt_long_press'' }}'
    sequence: !input 'button_3_remote_button_alt_long_press'
  - conditions:
    - '{{ command == ''button_4_remote_button_alt_long_press'' }}'
    sequence: !input 'button_4_remote_button_alt_long_press'
  - conditions:
    - '{{ command == ''button_5_remote_button_alt_long_press'' }}'
    sequence: !input 'button_5_remote_button_alt_long_press'
  - conditions:
    - '{{ command == ''button_6_remote_button_alt_long_press'' }}'
    sequence: !input 'button_6_remote_button_alt_long_press'
  - conditions:
    - '{{ command == ''button_1_remote_button_long_release'' }}'
    sequence: !input 'button_1_remote_button_long_release'
  - conditions:
    - '{{ command == ''button_2_remote_button_long_release'' }}'
    sequence: !input 'button_2_remote_button_long_release'
  - conditions:
    - '{{ command == ''button_3_remote_button_long_release'' }}'
    sequence: !input 'button_3_remote_button_long_release'
  - conditions:
    - '{{ command == ''button_4_remote_button_long_release'' }}'
    sequence: !input 'button_4_remote_button_long_release'
  - conditions:
    - '{{ command == ''button_5_remote_button_long_release'' }}'
    sequence: !input 'button_5_remote_button_long_release'
  - conditions:
    - '{{ command == ''button_6_remote_button_long_release'' }}'
    sequence: !input 'button_6_remote_button_long_release'